import { app, BrowserWindow, Menu, ipcMain, dialog, nativeTheme, shell } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import * as https from 'https';
import { SearchIndex } from './main/search-index';
import type { IndexedNoteRecord, SearchIndexStatus } from './main/search-index';
import type { ClaudeNotesAnswer, ClaudeSettings, MarkdownImportDecision, MarkdownImportInvalidFile, MarkdownImportResult, MarkdownImportScanResult } from './preload';
import type { IpcMainInvokeEvent, MenuItemConstructorOptions } from 'electron';
import { compareNoteFilenames, createUniqueGeneralNoteFilename, getNoteFolder, getNoteSummary, getTodayFilename, isJournalFilename, isNotePath, normalizeNotePath, type NoteSearchResult, type NoteSummary } from './shared/notes';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// --- Settings ---

interface AppSettings {
  notesFolder: string;
  noteTemplate: string;
  pinnedNotes: string[];
  claudeApiKey: string;
  claudeModel: string;
}

const DEFAULT_CLAUDE_MODEL = 'claude-3-5-sonnet-latest';
const settingsPath = path.join(app.getPath('userData'), 'settings.json');
const searchIndexPath = path.join(app.getPath('userData'), 'search-index.db');
const searchIndex = new SearchIndex(searchIndexPath);
const importSessions = new Map<string, { invalidFiles: MarkdownImportInvalidFile[]; candidates: Map<string, { filename: string; sourcePath: string; conflict: boolean }> }>();
let searchIndexDisabledReason: string | null = null;

function loadSettings(): AppSettings {
  const defaultFolder = path.join(app.getPath('documents'), 'mSlate Notes');
  const defaultSettings: AppSettings = {
    notesFolder: defaultFolder,
    noteTemplate: '',
    pinnedNotes: [],
    claudeApiKey: '',
    claudeModel: DEFAULT_CLAUDE_MODEL,
  };

  try {
    if (fs.existsSync(settingsPath)) {
      const raw = fs.readFileSync(settingsPath, 'utf-8');
      const parsed = JSON.parse(raw) as Partial<AppSettings>;
      return {
        notesFolder: typeof parsed.notesFolder === 'string' && parsed.notesFolder ? parsed.notesFolder : defaultSettings.notesFolder,
        noteTemplate: typeof parsed.noteTemplate === 'string' ? parsed.noteTemplate : defaultSettings.noteTemplate,
        pinnedNotes: Array.isArray(parsed.pinnedNotes) ? parsed.pinnedNotes : defaultSettings.pinnedNotes,
        claudeApiKey: typeof parsed.claudeApiKey === 'string' ? parsed.claudeApiKey : defaultSettings.claudeApiKey,
        claudeModel: typeof parsed.claudeModel === 'string' && parsed.claudeModel ? parsed.claudeModel : defaultSettings.claudeModel,
      };
    }
  } catch {
    // Corrupted settings — fall through to default
  }
  return defaultSettings;
}

function saveSettings(settings: AppSettings): void {
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
}

const settings = loadSettings();

nativeTheme.themeSource = 'dark';

function ensureNotesFolder(): void {
  if (!fs.existsSync(settings.notesFolder)) {
    fs.mkdirSync(settings.notesFolder, { recursive: true });
  }
}

// --- Helpers ---

function isSupportedImageMimeType(mimeType: string): boolean {
  return ['image/png', 'image/jpeg', 'image/gif', 'image/webp'].includes(mimeType);
}

function getImageExtension(mimeType: string): string {
  switch (mimeType) {
    case 'image/png':
      return 'png';
    case 'image/jpeg':
      return 'jpg';
    case 'image/gif':
      return 'gif';
    case 'image/webp':
      return 'webp';
    default:
      throw new Error('Unsupported image format');
  }
}

function getImageMimeTypeFromPath(filePath: string): string {
  switch (path.extname(filePath).toLowerCase()) {
    case '.png':
      return 'image/png';
    case '.jpg':
    case '.jpeg':
      return 'image/jpeg';
    case '.gif':
      return 'image/gif';
    case '.webp':
      return 'image/webp';
    default:
      return 'application/octet-stream';
  }
}

function ensureAttachmentsFolder(): string {
  ensureNotesFolder();
  const attachmentsFolder = path.join(settings.notesFolder, 'attachments');
  if (!fs.existsSync(attachmentsFolder)) {
    fs.mkdirSync(attachmentsFolder, { recursive: true });
  }
  return attachmentsFolder;
}

function createAttachmentFilename(noteFilename: string, extension: string): string {
  const basename = noteFilename.replace(/\.md$/i, '').replace(/[^a-zA-Z0-9_-]/g, '-');
  return `${basename}-${Date.now()}.${extension}`;
}

function normalizeAssetPath(assetPath: string): string {
  if (!assetPath || /^(https?:|data:|blob:|file:)/i.test(assetPath)) {
    return assetPath;
  }

  const normalized = path.normalize(assetPath).replace(/^([/\\])+/, '');
  if (normalized.startsWith('..') || path.isAbsolute(normalized)) {
    throw new Error('Invalid asset path');
  }

  return normalized;
}

function applyTemplate(template: string): string {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const dateStr = `${yyyy}-${mm}-${dd}`;
  const dayOfWeek = now.toLocaleDateString('en-US', { weekday: 'long' });
  return template
    .replace(/\{\{date\}\}/g, dateStr)
    .replace(/\{\{day_of_week\}\}/g, dayOfWeek);
}

function getNewNoteContent(filename: string): string {
  if (isJournalFilename(path.posix.basename(filename)) && settings.noteTemplate) {
    return applyTemplate(settings.noteTemplate);
  }

  return '';
}

function getAbsoluteNotePath(notePath: string): string {
  const normalizedPath = normalizeNotePath(notePath);
  const absolutePath = path.resolve(settings.notesFolder, ...normalizedPath.split('/'));
  const notesRoot = path.resolve(settings.notesFolder);
  if (!(absolutePath === notesRoot || absolutePath.startsWith(`${notesRoot}${path.sep}`))) {
    throw new Error('Invalid note path');
  }

  return absolutePath;
}

function collectNotePaths(directoryPath = settings.notesFolder, relativeDirectory = ''): string[] {
  const results: string[] = [];
  const entries = fs.readdirSync(directoryPath, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.name === 'attachments' && !relativeDirectory) {
      continue;
    }

    const relativePath = relativeDirectory ? `${relativeDirectory}/${entry.name}` : entry.name;
    const absolutePath = path.join(directoryPath, entry.name);

    if (entry.isDirectory()) {
      results.push(...collectNotePaths(absolutePath, relativePath.replace(/\\/g, '/')));
      continue;
    }

    const normalizedPath = relativePath.replace(/\\/g, '/');
    if (isNotePath(normalizedPath)) {
      results.push(normalizedPath);
    }
  }

  return results;
}

function removeEmptyParentDirectories(startPath: string): void {
  const notesRoot = path.resolve(settings.notesFolder);
  let currentPath = path.dirname(startPath);

  while (currentPath.startsWith(notesRoot) && currentPath !== notesRoot) {
    const entries = fs.readdirSync(currentPath);
    if (entries.length > 0) {
      return;
    }

    fs.rmdirSync(currentPath);
    currentPath = path.dirname(currentPath);
  }
}

function getIndexedNotes(): IndexedNoteRecord[] {
  ensureNotesFolder();
  return collectNotePaths()
    .map((filename) => ({
      filename,
      content: fs.readFileSync(getAbsoluteNotePath(filename), 'utf-8'),
    }));
}

function searchNotesLinear(query: string): NoteSearchResult[] {
  ensureNotesFolder();
  if (!query || query.trim().length === 0) return [];

  const searchTerm = query.toLowerCase();
  const files = collectNotePaths();
  const results: NoteSearchResult[] = [];

  for (const file of files) {
    const content = fs.readFileSync(getAbsoluteNotePath(file), 'utf-8');
    const lowerContent = content.toLowerCase();
    const idx = lowerContent.indexOf(searchTerm);
    if (idx !== -1) {
      const start = Math.max(0, idx - 30);
      const end = Math.min(content.length, idx + query.length + 50);
      const snippet = (start > 0 ? '...' : '') + content.substring(start, end).trim() + (end < content.length ? '...' : '');
      results.push({ note: getNoteSummary(file), snippet });
    }
  }

  return results.sort((a, b) => compareNoteFilenames(a.note.filename, b.note.filename));
}

function searchNotesWithFallback(query: string): NoteSearchResult[] {
  if (!query || query.trim().length === 0) {
    return [];
  }

  if (canUseSearchIndex()) {
    try {
      return searchIndex.searchNotes(query).map((result) => ({
        note: getNoteSummary(result.filename),
        snippet: result.snippet,
      }));
    } catch (error) {
      disableSearchIndex(error, 'search notes');
      console.error('Indexed search failed, falling back to linear search:', error);
    }
  }

  try {
    return searchNotesLinear(query);
  } catch (error) {
    console.error('Linear search failed:', error);
    return [];
  }
}

function getSearchIndexFallbackStatus(): SearchIndexStatus {
  return {
    ready: false,
    databasePath: searchIndexPath,
    notesFolder: settings.notesFolder,
    noteCount: 0,
    lastIndexedAt: null,
  };
}

function getSearchIndexStatusSafe(): SearchIndexStatus {
  try {
    const status = searchIndex.getStatus();
    if (searchIndexDisabledReason) {
      return { ...status, ready: false };
    }
    return status;
  } catch {
    return getSearchIndexFallbackStatus();
  }
}

function disableSearchIndex(error: unknown, action: string): void {
  const message = error instanceof Error ? error.message : String(error);
  if (!searchIndexDisabledReason) {
    console.error(`Search index disabled while attempting to ${action}:`, error);
  }
  searchIndexDisabledReason = message;
}

function canUseSearchIndex(): boolean {
  return !searchIndexDisabledReason;
}

function upsertIndexedNote(filename: string, content: string): void {
  if (!canUseSearchIndex()) {
    return;
  }

  try {
    searchIndex.upsertNote(filename, content);
  } catch (error) {
    disableSearchIndex(error, `index note ${filename}`);
  }
}

function removeIndexedNote(filename: string): void {
  if (!canUseSearchIndex()) {
    return;
  }

  try {
    searchIndex.removeNote(filename);
  } catch (error) {
    disableSearchIndex(error, `remove indexed note ${filename}`);
  }
}

function initializeSearchIndex(): SearchIndexStatus {
  if (!canUseSearchIndex()) {
    return getSearchIndexStatusSafe();
  }

  try {
    return searchIndex.initialize(settings.notesFolder, getIndexedNotes());
  } catch (error) {
    disableSearchIndex(error, 'initialize search index');
    return getSearchIndexStatusSafe();
  }
}

function rebuildSearchIndex(): SearchIndexStatus {
  if (!canUseSearchIndex()) {
    return getSearchIndexStatusSafe();
  }

  try {
    return searchIndex.rebuild(settings.notesFolder, getIndexedNotes());
  } catch (error) {
    disableSearchIndex(error, 'rebuild search index');
    return getSearchIndexStatusSafe();
  }
}

function clearSearchIndex(): SearchIndexStatus {
  if (!canUseSearchIndex()) {
    return getSearchIndexStatusSafe();
  }

  try {
    return searchIndex.clear(settings.notesFolder);
  } catch (error) {
    disableSearchIndex(error, 'clear search index');
    return getSearchIndexStatusSafe();
  }
}

function getClaudeSettings(): ClaudeSettings {
  return {
    apiKey: settings.claudeApiKey || '',
    model: settings.claudeModel || DEFAULT_CLAUDE_MODEL,
  };
}

function requireClaudeSettings(): ClaudeSettings {
  const claudeSettings = getClaudeSettings();
  if (!claudeSettings.apiKey.trim()) {
    throw new Error('Set your Anthropic API key in Settings before using Claude.');
  }

  return claudeSettings;
}

function postJson<T>(urlString: string, headers: Record<string, string>, body: unknown): Promise<T> {
  return new Promise((resolve, reject) => {
    const url = new URL(urlString);
    const payload = JSON.stringify(body);
    const request = https.request(
      {
        protocol: url.protocol,
        hostname: url.hostname,
        port: url.port,
        path: `${url.pathname}${url.search}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(payload).toString(),
          ...headers,
        },
      },
      (response) => {
        const chunks: Buffer[] = [];
        response.on('data', (chunk) => {
          chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
        });
        response.on('end', () => {
          const raw = Buffer.concat(chunks).toString('utf-8');
          const parsed = raw ? JSON.parse(raw) as { error?: { message?: string } } & T : {} as T;
          if ((response.statusCode ?? 500) >= 400) {
            reject(new Error(parsed.error?.message || `Anthropic request failed with status ${response.statusCode ?? 500}`));
            return;
          }

          resolve(parsed as T);
        });
      },
    );

    request.on('error', reject);
    request.write(payload);
    request.end();
  });
}

function extractClaudeText(response: { content?: Array<{ type: string; text?: string }> }): string {
  const text = (response.content ?? [])
    .filter((block) => block.type === 'text' && typeof block.text === 'string')
    .map((block) => block.text?.trim() ?? '')
    .filter((block) => block.length > 0)
    .join('\n\n');

  if (!text) {
    throw new Error('Claude returned an empty response.');
  }

  return text;
}

async function callClaude(system: string, prompt: string, maxTokens: number): Promise<string> {
  const claudeSettings = requireClaudeSettings();
  const response = await postJson<{ content?: Array<{ type: string; text?: string }> }>(
    'https://api.anthropic.com/v1/messages',
    {
      'x-api-key': claudeSettings.apiKey,
      'anthropic-version': '2023-06-01',
    },
    {
      model: claudeSettings.model,
      max_tokens: maxTokens,
      system,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    },
  );

  return extractClaudeText(response);
}

function getClaudeNoteContext(question: string): { context: string; sources: string[] } {
  const results = searchNotesWithFallback(question).slice(0, 8);
  const uniqueFiles = Array.from(new Set(results.map((result) => result.note.filename))).slice(0, 4);
  const sources: string[] = [];
  const sections: string[] = [];

  for (const filename of uniqueFiles) {
    try {
      const content = fs.readFileSync(getAbsoluteNotePath(filename), 'utf-8').trim();
      const snippet = results.find((result) => result.note.filename === filename)?.snippet ?? '';
      const excerpt = content.length > 5000 ? `${content.slice(0, 5000).trim()}\n...` : content;
      sections.push([
        `FILE: ${filename}`,
        snippet ? `SEARCH SNIPPET: ${snippet}` : '',
        'CONTENT:',
        excerpt,
      ].filter(Boolean).join('\n'));
      sources.push(filename);
    } catch (error) {
      console.error(`Failed to load note context for ${filename}:`, error);
    }
  }

  return {
    context: sections.join('\n\n---\n\n'),
    sources,
  };
}

function createImportSessionId(): string {
  return `import-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

function scanMarkdownImportFolder(folderPath: string): MarkdownImportScanResult {
  const validFiles: MarkdownImportScanResult['validFiles'] = [];
  const invalidFiles: MarkdownImportInvalidFile[] = [];
  const candidates = new Map<string, { filename: string; sourcePath: string; conflict: boolean }>();

  const entries = fs.readdirSync(folderPath, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile()) continue;

    const extension = path.extname(entry.name).toLowerCase();
    if (extension !== '.md') continue;

    const sourcePath = path.join(folderPath, entry.name);
    if (!isJournalFilename(entry.name)) {
      invalidFiles.push({ filename: entry.name, reason: 'Filename must match YYYY-MM-DD.md' });
      continue;
    }

    const id = createImportSessionId();
    const conflict = fs.existsSync(path.join(settings.notesFolder, entry.name));
    const candidate = { filename: entry.name, sourcePath, conflict };
    candidates.set(id, candidate);
    validFiles.push({ id, filename: entry.name, conflict });
  }

  const sessionId = createImportSessionId();
  importSessions.set(sessionId, { invalidFiles, candidates });

  return {
    sessionId,
    sourceFolder: folderPath,
    validFiles: validFiles.sort((a, b) => b.filename.localeCompare(a.filename)),
    invalidFiles: invalidFiles.sort((a, b) => a.filename.localeCompare(b.filename)),
  };
}

function applyMarkdownImport(sessionId: string, decisions: MarkdownImportDecision[]): MarkdownImportResult {
  const session = importSessions.get(sessionId);
  if (!session) {
    throw new Error('Import session expired');
  }

  const result: MarkdownImportResult = {
    imported: [],
    overwritten: [],
    skipped: [],
    invalid: session.invalidFiles,
    failed: [],
  };

  const decisionsById = new Map(decisions.map((decision) => [decision.id, decision.action]));

  for (const [id, candidate] of session.candidates.entries()) {
    const action = decisionsById.get(id) ?? (candidate.conflict ? 'skip' : 'import');
    if (action === 'skip') {
      result.skipped.push(candidate.filename);
      continue;
    }

    if (candidate.conflict && action !== 'overwrite') {
      result.skipped.push(candidate.filename);
      continue;
    }

    try {
      const content = fs.readFileSync(candidate.sourcePath, 'utf-8');
      const destinationPath = path.join(settings.notesFolder, candidate.filename);
      fs.writeFileSync(destinationPath, content, 'utf-8');
      upsertIndexedNote(candidate.filename, content);

      if (candidate.conflict) {
        result.overwritten.push(candidate.filename);
      } else {
        result.imported.push(candidate.filename);
      }
    } catch (error) {
      result.failed.push({
        filename: candidate.filename,
        reason: error instanceof Error ? error.message : 'Import failed',
      });
    }
  }

  importSessions.delete(sessionId);
  mainWindow?.webContents.send('notes-changed');
  return result;
}

// --- IPC Handlers ---

ipcMain.handle('get-today', () => {
  return getTodayFilename();
});

ipcMain.handle('create-note', async (_event, title: string): Promise<NoteSummary> => {
  ensureNotesFolder();
  const filename = createUniqueGeneralNoteFilename(title, collectNotePaths());
  const filePath = getAbsoluteNotePath(filename);
  const content = getNewNoteContent(filename);
  fs.writeFileSync(filePath, content, 'utf-8');
  upsertIndexedNote(filename, content);
  mainWindow?.webContents.send('notes-changed');
  return getNoteSummary(filename);
});

ipcMain.handle('delete-note', async (_event, filename: string): Promise<void> => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');

  const noteSummary = getNoteSummary(normalizedFilename);
  if (noteSummary.kind !== 'note') {
    throw new Error('Journal entries cannot be deleted.');
  }

  const filePath = getAbsoluteNotePath(normalizedFilename);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    removeEmptyParentDirectories(filePath);
  }

  removeIndexedNote(normalizedFilename);

  if (!settings.pinnedNotes) {
    settings.pinnedNotes = [];
  }
  const nextPinnedNotes = settings.pinnedNotes.filter((entry) => entry !== normalizedFilename);
  if (nextPinnedNotes.length !== settings.pinnedNotes.length) {
    settings.pinnedNotes = nextPinnedNotes;
    saveSettings(settings);
  }

  mainWindow?.webContents.send('notes-changed');
});

ipcMain.handle('read-note', async (_event, filename: string) => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');
  ensureNotesFolder();
  const filePath = getAbsoluteNotePath(normalizedFilename);
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf-8');
  }
  const content = getNewNoteContent(normalizedFilename);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
  upsertIndexedNote(normalizedFilename, content);
  return content;
});

ipcMain.handle('write-note', async (_event, filename: string, content: string) => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');
  ensureNotesFolder();
  const filePath = getAbsoluteNotePath(normalizedFilename);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tmpPath = filePath + '.tmp';
  // Atomic write: write to temp file, then rename
  fs.writeFileSync(tmpPath, content, 'utf-8');
  fs.renameSync(tmpPath, filePath);
  upsertIndexedNote(normalizedFilename, content);
});

ipcMain.handle('save-pasted-image', async (_event, filename: string, mimeType: string, bytes: number[]) => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');
  if (!isSupportedImageMimeType(mimeType)) throw new Error('Unsupported image format');
  if (!Array.isArray(bytes) || bytes.length === 0) throw new Error('Image data is required');

  const attachmentsFolder = ensureAttachmentsFolder();
  const extension = getImageExtension(mimeType);
  const attachmentFilename = createAttachmentFilename(normalizedFilename, extension);
  const attachmentPath = path.join(attachmentsFolder, attachmentFilename);
  fs.writeFileSync(attachmentPath, Buffer.from(bytes));

  const noteFolder = getNoteFolder(normalizedFilename);
  const relativeAssetPath = path.relative(
    noteFolder ? path.join(settings.notesFolder, ...noteFolder.split('/')) : settings.notesFolder,
    attachmentPath,
  ).replace(/\\/g, '/');

  return relativeAssetPath;
});

ipcMain.handle('resolve-note-asset-url', async (_event, filename: string, assetPath: string) => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');

  const normalizedAssetPath = normalizeAssetPath(assetPath);
  if (!normalizedAssetPath || /^(https?:|data:|blob:|file:)/i.test(normalizedAssetPath)) {
    return normalizedAssetPath || null;
  }

  ensureNotesFolder();
  const notesRoot = path.resolve(settings.notesFolder);
  const noteDirectory = path.dirname(getAbsoluteNotePath(normalizedFilename));
  const resolvedPath = path.resolve(noteDirectory, normalizedAssetPath);
  if (!(resolvedPath === notesRoot || resolvedPath.startsWith(`${notesRoot}${path.sep}`))) {
    return null;
  }

  if (!fs.existsSync(resolvedPath)) {
    return null;
  }

  const mimeType = getImageMimeTypeFromPath(resolvedPath);
  const fileBuffer = fs.readFileSync(resolvedPath);
  return `data:${mimeType};base64,${fileBuffer.toString('base64')}`;
});

ipcMain.handle('list-notes', async () => {
  ensureNotesFolder();
  return collectNotePaths()
    .sort(compareNoteFilenames)
    .map(getNoteSummary);
});

ipcMain.handle('search-notes', async (_event, query: string) => {
  return searchNotesWithFallback(query);
});

ipcMain.handle('get-notes-folder', () => {
  return settings.notesFolder;
});

ipcMain.handle('open-notes-folder', async () => {
  ensureNotesFolder();
  const errorMessage = await shell.openPath(settings.notesFolder);
  if (errorMessage) {
    throw new Error(errorMessage);
  }
  return true;
});

ipcMain.handle('choose-notes-folder', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
    title: 'Choose Notes Folder',
  });
  if (!result.canceled && result.filePaths.length > 0) {
    settings.notesFolder = result.filePaths[0];
    saveSettings(settings);
    ensureNotesFolder();
    rebuildSearchIndex();
    startWatchingNotes();
    mainWindow?.webContents.send('notes-changed');
    return settings.notesFolder;
  }
  return null;
});

ipcMain.handle('get-search-index-status', () => {
  return getSearchIndexStatusSafe();
});

ipcMain.handle('rebuild-search-index', () => {
  return rebuildSearchIndex();
});

ipcMain.handle('clear-search-index', () => {
  return clearSearchIndex();
});

ipcMain.handle('choose-markdown-import-folder', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
    title: 'Choose Folder With Markdown Notes',
  });

  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }

  return scanMarkdownImportFolder(result.filePaths[0]);
});

ipcMain.handle('apply-markdown-import', async (_event, sessionId: string, decisions: MarkdownImportDecision[]) => {
  return applyMarkdownImport(sessionId, decisions);
});

ipcMain.handle('get-template', () => {
  return settings.noteTemplate;
});

ipcMain.handle('set-template', async (_event, template: string) => {
  settings.noteTemplate = template;
  saveSettings(settings);
});

ipcMain.handle('get-claude-settings', () => {
  return getClaudeSettings();
});

ipcMain.handle('set-claude-settings', async (_event, claudeSettings: ClaudeSettings) => {
  settings.claudeApiKey = typeof claudeSettings.apiKey === 'string' ? claudeSettings.apiKey.trim() : '';
  settings.claudeModel = typeof claudeSettings.model === 'string' && claudeSettings.model.trim()
    ? claudeSettings.model.trim()
    : DEFAULT_CLAUDE_MODEL;
  saveSettings(settings);
});

ipcMain.handle('claude-summarize-selection', async (_event, selection: string, filename?: string) => {
  const text = selection.trim();
  if (!text) {
    throw new Error('Select some text before asking Claude to summarize it.');
  }

  const noteLabel = filename ? `\nCurrent note: ${filename}` : '';
  return callClaude(
    'You summarize selected passages from a markdown note. Preserve factual meaning. Keep markdown structure when it matters. Return only the rewritten text with no commentary.',
    `Summarize the following selected text from a note.${noteLabel}\n\nSELECTED TEXT:\n${text}`,
    700,
  );
});

ipcMain.handle('claude-rewrite-selection', async (_event, selection: string, filename?: string) => {
  const text = selection.trim();
  if (!text) {
    throw new Error('Select some text before asking Claude to rewrite it.');
  }

  const noteLabel = filename ? `\nCurrent note: ${filename}` : '';
  return callClaude(
    'You rewrite selected passages from a markdown note. Improve clarity and flow while preserving meaning, factual content, and markdown structure. Return only the rewritten text with no commentary.',
    `Rewrite the following selected text for clarity and readability.${noteLabel}\n\nSELECTED TEXT:\n${text}`,
    900,
  );
});

ipcMain.handle('claude-ask-notes', async (_event, question: string): Promise<ClaudeNotesAnswer> => {
  const normalizedQuestion = question.trim();
  if (!normalizedQuestion) {
    throw new Error('Enter a question before asking Claude about your notes.');
  }

  const noteContext = getClaudeNoteContext(normalizedQuestion);
  if (!noteContext.context) {
    return {
      answer: 'I could not find relevant note context for that question.',
      sources: [],
    };
  }

  const answer = await callClaude(
    'You answer questions about a user\'s personal markdown notes. Use only the supplied note context. If the context is insufficient, say that clearly. Be concise and practical. Mention source filenames in the answer when relevant.',
    `Question: ${normalizedQuestion}\n\nNOTE CONTEXT:\n${noteContext.context}`,
    1200,
  );

  return {
    answer,
    sources: noteContext.sources,
  };
});

ipcMain.handle('get-pinned-notes', () => {
  return settings.pinnedNotes || [];
});

ipcMain.handle('toggle-pin', async (_event, filename: string) => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');
  if (!settings.pinnedNotes) settings.pinnedNotes = [];
  const idx = settings.pinnedNotes.indexOf(normalizedFilename);
  if (idx === -1) {
    settings.pinnedNotes.push(normalizedFilename);
  } else {
    settings.pinnedNotes.splice(idx, 1);
  }
  saveSettings(settings);
  return settings.pinnedNotes;
});

// --- Window ---

let mainWindow: BrowserWindow | null = null;
let notesWatcher: fs.FSWatcher | null = null;
let searchSyncTimeout: ReturnType<typeof setTimeout> | null = null;

function scheduleSearchIndexSync(): void {
  if (searchSyncTimeout) clearTimeout(searchSyncTimeout);
  searchSyncTimeout = setTimeout(() => {
    searchSyncTimeout = null;
    try {
      rebuildSearchIndex();
    } catch (error) {
      console.error('Failed to synchronize search index:', error);
    }
  }, 200);
}

function startWatchingNotes(): void {
  stopWatchingNotes();
  ensureNotesFolder();
  notesWatcher = fs.watch(settings.notesFolder, { recursive: true }, (_eventType, filename) => {
    if (filename && isNotePath(filename.replace(/\\/g, '/')) && mainWindow) {
      mainWindow.webContents.send('notes-changed');
      scheduleSearchIndexSync();
    }
  });
}

function stopWatchingNotes(): void {
  if (searchSyncTimeout) {
    clearTimeout(searchSyncTimeout);
    searchSyncTimeout = null;
  }
  if (notesWatcher) {
    notesWatcher.close();
    notesWatcher = null;
  }
}

function getEventWindow(event: IpcMainInvokeEvent): BrowserWindow {
  const window = BrowserWindow.fromWebContents(event.sender);
  if (!window) {
    throw new Error('No window available');
  }

  return window;
}

ipcMain.handle('export-pdf', async (_event, filename: string) => {
  const normalizedFilename = normalizeNotePath(filename);
  if (!isNotePath(normalizedFilename)) throw new Error('Invalid note filename');
  if (!mainWindow) throw new Error('No window available');

  const exportName = path.posix.basename(normalizedFilename, '.md');
  const result = await dialog.showSaveDialog(mainWindow, {
    defaultPath: `mSlate-${exportName}.pdf`,
    filters: [{ name: 'PDF', extensions: ['pdf'] }],
  });
  if (result.canceled || !result.filePath) return false;

  const pdfData = await mainWindow.webContents.printToPDF({
    printBackground: true,
    margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.5 },
  });
  fs.writeFileSync(result.filePath, pdfData);
  return true;
});

ipcMain.handle('get-window-state', async (event) => {
  const window = getEventWindow(event);
  return {
    isDesktop: true,
    isMaximized: window.isMaximized(),
  };
});

ipcMain.handle('minimize-window', async (event) => {
  getEventWindow(event).minimize();
});

ipcMain.handle('toggle-maximize-window', async (event) => {
  const window = getEventWindow(event);
  if (window.isMaximized()) {
    window.unmaximize();
    return false;
  }

  window.maximize();
  return true;
});

ipcMain.handle('close-window', async (event) => {
  getEventWindow(event).close();
});

ipcMain.handle('reload-window', async (event) => {
  getEventWindow(event).reload();
});

ipcMain.handle('toggle-devtools', async (event) => {
  getEventWindow(event).webContents.toggleDevTools();
});

ipcMain.handle('quit-app', async () => {
  app.quit();
});

function buildApplicationMenu(): void {
  const isMac = process.platform === 'darwin';
  const macAppSubmenu: MenuItemConstructorOptions[] = [
    { role: 'about' },
    { type: 'separator' },
    { role: 'services' },
    { type: 'separator' },
    { role: 'hide' },
    { role: 'hideOthers' },
    { role: 'unhide' },
    { type: 'separator' },
    { role: 'quit' },
  ];
  const fileSubmenu: MenuItemConstructorOptions[] = [
    {
      label: 'Open Notes Folder',
      click: async () => {
        ensureNotesFolder();
        await shell.openPath(settings.notesFolder);
      },
    },
    { type: 'separator' },
    {
      label: 'Open Settings',
      accelerator: 'CmdOrCtrl+,',
      click: () => {
        mainWindow?.webContents.executeJavaScript("window.dispatchEvent(new KeyboardEvent('keydown', { key: ',', ctrlKey: true }))");
      },
    },
    { type: 'separator' },
    { role: 'quit' },
  ];
  const editSubmenu: MenuItemConstructorOptions[] = [
    { role: 'undo' },
    { role: 'redo' },
    { type: 'separator' },
    { role: 'cut' },
    { role: 'copy' },
    { role: 'paste' },
    { role: 'pasteAndMatchStyle' },
    { role: 'delete' },
    { role: 'selectAll' },
  ];
  const viewSubmenu: MenuItemConstructorOptions[] = [
    { role: 'reload' },
    { role: 'forceReload' },
    { role: 'toggleDevTools' },
    { type: 'separator' },
    { role: 'resetZoom' },
    { role: 'zoomIn' },
    { role: 'zoomOut' },
    { type: 'separator' },
    { role: 'togglefullscreen' },
  ];
  const windowSubmenu: MenuItemConstructorOptions[] = isMac
    ? [{ role: 'minimize' }, { role: 'zoom' }, { role: 'front' }, { type: 'separator' }, { role: 'window' }]
    : [{ role: 'minimize' }, { role: 'zoom' }, { role: 'close' }];
  const helpSubmenu: MenuItemConstructorOptions[] = [
    {
      label: 'About mSlate',
      role: 'about',
    },
  ];

  const template: MenuItemConstructorOptions[] = [
    ...(isMac ? [{ label: app.name, submenu: macAppSubmenu }] : []),
    {
      label: 'File',
      submenu: fileSubmenu,
    },
    {
      label: 'Edit',
      submenu: editSubmenu,
    },
    {
      label: 'View',
      submenu: viewSubmenu,
    },
    {
      label: 'Window',
      submenu: windowSubmenu,
    },
    {
      label: 'Help',
      submenu: helpSubmenu,
    },
  ];

  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

function broadcastWindowState(): void {
  if (!mainWindow) return;

  mainWindow.webContents.send('window-state-changed', {
    isDesktop: true,
    isMaximized: mainWindow.isMaximized(),
  });
}

const createWindow = (): void => {
  initializeSearchIndex();
  if (process.platform === 'darwin') {
    buildApplicationMenu();
  } else {
    Menu.setApplicationMenu(null);
  }

  mainWindow = new BrowserWindow({
    height: 700,
    width: 1100,
    minWidth: 600,
    minHeight: 400,
    backgroundColor: '#1a1a2e',
    title: `mSlate — ${getTodayFilename().replace('.md', '')}`,
    frame: process.platform === 'darwin',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'hidden',
    autoHideMenuBar: process.platform !== 'darwin',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.setMenuBarVisibility(process.platform === 'darwin');

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  startWatchingNotes();

  mainWindow.on('maximize', broadcastWindowState);
  mainWindow.on('unmaximize', broadcastWindowState);

  mainWindow.on('closed', () => {
    stopWatchingNotes();
    mainWindow = null;
  });

  // Update title when note changes
  ipcMain.on('set-title', (_event, noteTitle: string) => {
    if (mainWindow) mainWindow.setTitle(`mSlate \u2014 ${noteTitle}`);
  });
};

app.on('ready', createWindow);

app.on('before-quit', () => {
  stopWatchingNotes();
  searchIndex.close();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
